#! /usr/bin/perl



my $filename = 'testfile.txt';

sub Test {
    #my $filename = 'testfile.txt':
    
    print "$filename\n";

    my $timeout = scalar localtime();

    print "$timeout\n";

    while (1) {

        print "entered loop\n";

        my $current_mtime = (stat $filename)[9];

        sleep(1);

        my $updated_mtime = (stat $filename)[9];

        if ($updated_mtime > $current_mtime) {
            print "file has been changed"
        }
    }
}

Test();
